### ISSUE TITLE
TiledOG.CreateStage() returns undefined

### ISSUE THREAD

**Issue by cadhead** [eXponenta/pixi-tiled#2]
I tried to check out youre demo, but getting this error.

**Comment by eXponenta** [comment]
https://exponenta.github.io/pixi-tiled/demo/dist/

I checked it, works fine.

Can you include example or json file, which you try load? Because parcing will be skiped if json invalid

I finished 5 project with this package without any problems, but i think, i must refact it and create documentation:)

**Comment by eXponenta** [comment]
Вообще, можно писать и на славянском  =)

**Comment by cadhead** [comment]
Прошу прощения. Проблема была в codesandbox который, оказывается, вообще не давал загрузить ассеты.
Если кто-нибудь ещё захочет чекнуть демку там — для загрузки ассетов надо использовать require().

**Comment by eXponenta** [comment]
Нет, там нужно просто ложить в верную папку и грузить с правильным адресом =)
А так же выставлять ресурсам crossorigin: "Anonymous"
